### ISSUE TITLE
Build script fails for VS 2017 editions other than Enterprise Edition

### ISSUE THREAD

**Issue by vcaraulean** [atifaziz/LinqPadless#14]
The path in `build.cmd` points to Enterprise edition of VS2017.

To work on any VS installation (as Professional, Community) the script can be smarter in finding `msbuild.exe`:
 - probe/enumerate for different editions
 - [vswhere](https://github.com/Microsoft/vswhere)
 - [vssetup.powershell](https://github.com/Microsoft/vssetup.powershell)

**Comment by atifaziz** [comment]
@vcaraulean Thanks for bringing this up. I've changed the title so this sounds and can be classified more like a bug.

**Comment by atifaziz** [comment]
@vcaraulean Let me know if the fix in #15 helps, which takes the ”probe/enumerate for different editions“ strategy.

**Comment by vcaraulean** [comment]
Yes, seems to be working for me.
