### ISSUE TITLE
Support namespace declarations (starting with LINQPad 6) in queries

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/LinqPadless#29]
Investigate and add support for namespace declarations in queries that's coming with LINQPad 6, per following [tweet](https://twitter.com/linqpad/status/1171354519252287492) by @albahari:

> LINQPad 6 now lets you define namespaces, making it easier to paste in code from VS. And to help with navigation, there's now full bookmarking support - with both VS and ReSharper hotkey compatibility.
>
> ![](https://pbs.twimg.com/media/EEF8uX1UEAAFwqR?format=png&name=900x900)

**Comment by albahari** [comment]
The trick is to first parse the query as a script - from that, you can identify any namespace declarations (as well as classes that contain extension methods). Then you'll know which ranges to include outside the UserQuery class. 

You will also need to include the following import:

`using static global::UserQuery`

so that the constructs outside the UserQuery can still see its static members.

**Comment by atifaziz** [comment]
Hey @albahari, thanks for dropping in! The technique you describe is close to what I am already doing with Program-style queries where `Main` and type declarations need to be split out (especially if they contain extension methods as they cannot belong in a nested type):

https://github.com/atifaziz/LinqPadless/blob/480b54bea6d87e902d009ba1122b28db3df90e16/src/Program.cs#L690-L705

I am guessing then that scanning and extracting namespace declarations shouldn't be much work from here.

> You will also need to include the following import:
> 
> `using static global::UserQuery`
> 
> so that the constructs outside the UserQuery can still see its static members.

Interesting. I hadn't considered that and thanks again for offering these tips. It will help me keep as much parity with LINQPad as possible, as far as the transformation of the script into a runnable program goes.

**Comment by albahari** [comment]
Yes, it's not too much work, once you figure out the trick. LINQPad used to first wrap the code in the UserQuery class and then extract constructs such as classes that contain extension methods. But this approach doesn't work reliably with namespaces, so you have to parse it first without the UserQuery class, and with the SourceCodeKind.Script option. The resultant SyntaxTree will still contain errors complaining about the illegal namespaces, but the offsets for when the namespaces start and end will all be correct.

**Comment by atifaziz** [comment]
> LINQPad used to first wrap the code in the UserQuery class and then extract constructs such as classes that contain extension methods.

I was doing the same but reading that, I discovered a bug (#30) where all types were being floated outside `UserQuery` instead of just those containing extension methods.

> But this approach doesn't work reliably with namespaces, so you have to parse it first without the UserQuery class, and with the SourceCodeKind.Script option. The resultant SyntaxTree will still contain errors complaining about the illegal namespaces, but the offsets for when the namespaces start and end will all be correct.

Thanks again for sharing what worked for you internally. 👍 It'll be tremendous help in getting this support in.

**Comment by atifaziz** [comment]
> But this approach doesn't work reliably with namespaces

@albahari Do you remember a construct where that doesn't work, which deems it as unreliable or risky? I mean if parsing errors can be tolerated then a namespace declaration appearing in class declaration such as `UserQuery` would also work to just get the offsets.

What I want to avoid is the performance hit of having to parse twice, once with `SourceCodeKind.Script` and then again with `SourceCodeKind.Regular`, unless of course, you've found that a single pass with `SourceCodeKind.Script` alone was good enough?

**Comment by albahari** [comment]
I seem to remember it getting the offsets wrong when there are classes following the namespace. I performance-tested the extra parse, and it was minimal relative to the cost of the subsequent bind and emit phases.
