### ISSUE TITLE
Support C# Program queries where Main is async

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/LinqPadless#3]
If `Main` is async then call to it needs to be awaited. For example:

``` c#
async Task Main()
{
    await Task.Delay(TimeSpan.FromSeconds(1));
    Console.WriteLine(DateTime.Now);
}
```

should become:

``` c#
async Task Main()
{
    await Task.Delay(TimeSpan.FromSeconds(1));
    Console.WriteLine(DateTime.Now);
}

await Main(); // added by LINQPadless
```

One option, albeit a little heavy-handed, would be to use Roslyn to parse and determine whether `Main` is async or not.

---

Forked from #2

**Comment by shamork** [comment]
IMO, it's ok that simply add an "await" when there is an "async" before the main function.
The first thing is "can do", then "do it pretty"!

**Comment by atifaziz** [comment]
> when there is an "async" before the main function.

How do you find `Main` in the code? What if there's a trial version of some `Main` that's commented out (or conditionally compiled out) and using a quick & dirty trick like regular expressions to sniff out the `async` before `Main` picks on the wrong thing?

> The first thing is "can do", then "do it pretty"!

True but often when you have it working one way then there's a lesser urge to make it pretty. :)

**Comment by atifaziz** [comment]
Seems the code to do so is trivial with Roslyn:

```c#
var tests =
    from source in new[]
    {
        @"
        /*
        async Task Main() {
            await Task.Delay(TimeSpan.FromSeconds(1));
            Console.WriteLine(DateTime.Now);
        }
        */
        async void Foo() {}
        void Main() {}
        ",
        
        @"
        async void Foo() {}
        async void Main() {
            await Task.Delay(TimeSpan.FromSeconds(1));
            Console.WriteLine(DateTime.Now);
        }
        "
    }
    select
        CSharpSyntaxTree.ParseText(source).GetRoot()
            .DescendantNodes().OfType<MethodDeclarationSyntax>()
            .Any(md => "Main" == (string) md.Identifier.Text
                       && md.Modifiers.Any(m => m.IsKind(SyntaxKind.AsyncKeyword)));

foreach (var test in tests)
    Console.WriteLine(test);
```
