### ISSUE TITLE
How LinqPadless V1.1 support netstandard 2.0? 

### ISSUE THREAD

**Issue by shps951023** [atifaziz/LinqPadless#45]
e.g : 
If system add ref of netstandard 2.0 project then command `lpless.exe -t exe "path"`   will get below error msg : 

> error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

even i add `LINQPad5\netstandard2` then system still not work
![image](https://user-images.githubusercontent.com/12729184/84104213-a53f2400-aa47-11ea-960c-7bf2edcde80c.png)
![image](https://user-images.githubusercontent.com/12729184/84104227-b0924f80-aa47-11ea-9c4f-ebb914a388d0.png)

PS:
LinqPadless version is V1.1.

**Comment by atifaziz** [comment]
LINQPad queries are _applications_, not libraries. They target runtimes. The .NET Standard is for libraries, so the question whether LINQPadless supports the standard doesn't apply. Also, .NET Standard is a reference to a standardized API surface as opposed to an implementation.
