### ISSUE TITLE
Nuget error attempting to query latest version of SSH.NET

### ISSUE THREAD

**Issue by NetMage** [atifaziz/LinqPadless#48]
Using lpless on script that uses SSH.NET from nuget, I get an error:

  Packages directory: N:\LINQPad Queries\packages
  Packages target: .NETFramework,Version=v4.5.2
  Querying latest version of SSH.NET
Unable to load the service index for source https://api.nuget.org/v3/index.json.

Could this be because I need to configure a Proxy?

**Comment by atifaziz** [comment]
> Could this be because I need to configure a Proxy?

Does your environment generally need a proxy configured for Internet access? Does this error occur no matter which package you try to reference? That is, it's not specific to referencing SSH.NET?

**Comment by atifaziz** [comment]
Closing due to no follow-up.
