### ISSUE TITLE
LinqPadless 1.1 - SSL certificate error

### ISSUE THREAD

**Issue by veremenko-y** [atifaziz/LinqPadless#49]
I know you've decided to convert new version to .NET core ( :( ) but I still use LinqPad 5. Latest 1.1 version seems to fail due to the SSL issues. Is it possible to patch it and release an update?

This is what I was getting on the first run.

    PS D:\...> lpless .\script.linq -t exe
    D:\...\script.linq
      Packages directory: D:\...\packages
      Packages target: .NETFramework,Version=v4.5.2
      Installing C# compiler using NuGet:
        Downloading NuGet from https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe
    The request was aborted: Could not create SSL/TLS secure channel.

After going over the source code, I managed to download csc manually and put it in the folder that lqless wants it to be, but that doesn't fully help, as you can see.

    D:\...\script.linq
      Packages directory: D:\...\packages
      Packages target: .NETFramework,Version=v4.5.2
      Querying latest version of FakeLinqPad
    An error occurred while retrieving package metadata for 'FakeLinqPad' from source 'https://api.nuget.org/v3/index.json'.

**Comment by atifaziz** [comment]
I think this might be related to [nuget.org permanently removing support for TLS 1.0 and 1.1](https://devblogs.microsoft.com/nuget/nuget-org-will-permanently-remove-support-for-tls-1-0-and-1-1-on-june-15th/).

>  Is it possible to patch it and release an update?

I'd be happy to take a PR and make a release if you can help with spotting the problem and then fixing and testing it (assuming it's urgent to you).

**Comment by atifaziz** [comment]
Something else to consider that may not require any code changes:

- [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls), specifically section "[For .NET Framework 3.5 - 4.5.2 and not WCF](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#for-net-framework-35---452-and-not-wcf)".

**Comment by veremenko-y** [comment]
Not very urgent, I hacked around with current version to make it work for now. But I did made a simple PR that fixes this particular issue and enforces TSL 1.2.

**Comment by atifaziz** [comment]
> Not very urgent, I hacked around with current version to make it work for now. But I did made a simple PR that fixes this particular issue and enforces TSL 1.2.

Thanks, but the [build has failed](https://ci.appveyor.com/project/raboof/linqpadless/builds/37031598) and I am afraid I don't have much time to investigate.

Did you checkout the other workaround mentioned in the links I shared? Most of the those don't seems to need any code changes.

**Comment by veremenko-y** [comment]
> Thanks, but the [build has failed](https://ci.appveyor.com/project/raboof/linqpadless/builds/37031598) and I am afraid I don't have much time to investigate.

Nuget packages were not restored. I'm not familiar with appveyor at all, so I don't know why. Project is built without errors locally in Debug and Release configurations.
 
> Did you checkout the other workaround mentioned in the links I shared? Most of the those don't seems to need any code changes.

Correct. But the app is available to download in nuget and scoop https://github.com/lukesampson/scoop-extras/blob/a8bcb1b43b0230a9348a422017be31fe625cea70/bucket/linqpadless.json, but TLS issue makes it completely broken out of the box.

I wanted to fix it for everybody, not just me. It's still useful tool, even though it's technically outdated with release of new LINQPad (although v5 is still supported) and .NET. I understand that you are busy and may not have time to deal with this, but without access to build infrastructure I'm unable to help any further. Feel free to close the issue and pr.

**Comment by atifaziz** [comment]
Closed via a2e6352875fa81d1e381db57fbc0f521209df550 that is the merge of PR #50.

**Comment by atifaziz** [comment]
The fix is now available in [release 1.2](https://github.com/atifaziz/LinqPadless/releases/tag/v1.2.0).

**Comment by veremenko-y** [comment]
This is amazing, thank you!

**Comment by veremenko-y** [comment]
I'm really sorry, now I feel even worse. It still doesn't work on clean install. Because you moved setting `SecurityProtocol` down next to downloading nuget references, it will be unable to download `csc` from Nuget when running `lpless script.linq -t exe`...

**Comment by atifaziz** [comment]
> Because you moved setting `SecurityProtocol` down next to downloading nuget references, it will be unable to download `csc` from Nuget when running `lpless script.linq -t exe`...

That's too bad. I guess what happened here was that I always tested against a LINQPad query file that referenced a NuGet package and so the TLS was always upgraded by the time it got to the compilation step and which downloaded `nuget.exe` and the compiler.
