### ISSUE TITLE
VS Projects not loading

### ISSUE THREAD

**Issue by tadrian** [atifaziz/LinqPadless#54]
I downloaded the solution and opened it in VS 2019 on windows 10, Projects can't be loaded, get the following errors

LinqPadless-master\src\LinqPadless.csproj : error  : The project file cannot be opened. The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'

LinqPadless-master\tests\Tests.csproj : error  : The project file cannot be opened. The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'

LinqPadless-master\.lpless\templates\template\ProgramTemplate.csproj : error  : The project file cannot be opened. The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'

**Comment by atifaziz** [comment]
There is a [`global.json`](https://github.com/atifaziz/LinqPadless/blob/f452faa66dc124f085ccf2a924fcfa7e3a343a27/global.json) in that pins to the SDK that was used to develop LINQPadless. I suspect that might the problem. It's possible you don't have .NET Core SDK 3.1.101+ installed so either [you should install that version](https://dotnet.microsoft.com/en-us/download/dotnet/3.1) or you can try and delete `global.json` locally to see if it works with the latest SDK you have on your machine.

**Comment by tadrian** [comment]
thanks, removed the global.json and switched to Net5.0, compiled ok
