### ISSUE TITLE
Documentation: Release

### ISSUE THREAD

**Issue by runxc1** [atifaziz/LinqPadless#6]
Is there a Release somewhere that can be downloaded.  Also what does the .csx file look like and how are you running the .csx file?

**Comment by atifaziz** [comment]
> Is there a Release somewhere that can be downloaded.

Not yet. Meanwhile you can [download a zip](https://github.com/linqpadless/LinqPadless/archive/master.zip) of the repo and build locally by running `build.cmd`. If you open an issue around just the release topic then you can follow up and get notified when it's available.

> Also what does the .csx file look like

So let's say you have a `test.linq` file with the following C# statements to dump out the individual paths in the `PATH` environment variable:

``` c#
foreach (var path in Environment.GetEnvironmentVariable("PATH").Split(';'))
    Console.WriteLine(path);
```

Running LinqPadless on it like this:

```
lpless test.linq
```

will give the following output:

```
A:\tmp\test.linq
  Packages directory: A:\packages
  Packages target: .NETFramework,Version=v4.5.2
```

The generated C# script will look like this:

``` c#
#r "System.dll"
#r "Microsoft.CSharp.dll"
#r "System.Core.dll"
#r "System.Data.dll"
#r "System.Data.Entity.dll"
#r "System.Transactions.dll"
#r "System.Xml.dll"
#r "System.Xml.Linq.dll"
#r "System.Data.Linq.dll"
#r "System.Drawing.dll"
#r "System.Data.DataSetExtensions.dll"

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;
using System.Threading;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data;
using System.Data.SqlClient;
using System.Data.Linq;
using System.Data.Linq.SqlClient;
using System.Transactions;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
foreach (var path in Environment.GetEnvironmentVariable("PATH").Split(';'))
    Console.WriteLine(path);
```

> how are you running the .csx file?

LinqPadless will also generate a Windows batch script next to `test.csx` called `test.cmd` with the following content:

```
@echo off
setlocal
set LINQPADLESS=1.0.19706.704
for %%i in (csi.exe) do set CSIPATH=%%~$PATH:i
if defined CSIPATH goto :boot
if defined ProgramFiles(x86) set CSIPATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin\csi.exe && goto :boot
set CSIPATH=%ProgramFiles%\MSBuild\14.0\Bin\csi.exe
:boot
if not exist "%CSIPATH%" goto :nocsi
pushd "%~dp0"

:run
popd
if %errorlevel%==0 "%CSIPATH%" "%~dpn0.csx" -- %*
goto :EOF

:pkgerr
popd
exit /b %errorlevel%

:nocsi
>&2 echo Microsoft (R) Visual C# Interactive Compiler does not appear to be
>&2 echo installed. You can download it as part of Microsoft Build Tools 2015
>&2 echo using the URL below, install and try again:
>&2 echo https://www.microsoft.com/en-us/download/details.aspx?id=48159
exit /b 1
```

The batch script allows you to simply type `test` at the command prompt to run the C# script and invokes the C# interpreter (`csi.exe`) passing it the C# script file.

**Comment by atifaziz** [comment]
Here's an animated demo posted a few days ago:

![LinqPadless demo](https://cloud.githubusercontent.com/assets/20511/16429794/e83f6cdc-3d78-11e6-9490-764d64aab99b.gif)

**Comment by runxc1** [comment]
Hey thanks for the feedback.  I had to download the command line version of nuget but was able to build the project and gave it a try.

Perhaps this is a limitation but it didn't seem that it was able to handle the nuget and .dll references as when I ran the .cmd file that it generated I got an error on the following lines within the small script that I had written.  Is there a way to even add the following references in a .csx file?

ref nuget:EntityFramework;
ref nuget:mongocsharpdriver;
ref nuget:EPPlus;
ref C:\dev\tools\linqpad\dlls\MyLib.Common.dll;

**Comment by atifaziz** [comment]
> I had to download the command line version of nugget

Could you [report that as an issue](https://github.com/linqpadless/LinqPadless/issues/new)? If it requires NuGet and it's absent then it should say so.

> Perhaps this is a limitation but it didn't seem that it was able to handle the nuget and .dll references as when I ran the .cmd file that it generated I got an error on the following lines within the small script that I had written.

Again, whether this is a limitation or an issue, best if we take that up as [a separate issue](https://github.com/linqpadless/LinqPadless/issues/new) as this one has been closed based on your [original questions](https://github.com/linqpadless/LinqPadless/issues/6#issue-162548324) and subject of release.

**Comment by atifaziz** [comment]
FYI, [release 1.0 is now available over NuGet](https://www.nuget.org/packages/LinqPadless/1.0.0).
