### ISSUE TITLE
support for database queries ?

### ISSUE THREAD

**Issue by areagu** [atifaziz/LinqPadless#7]
does this tool support for linq to sql queries ??

so this tool is an amazing idea...
but i tried the following and it didn't work:

connect to local mssql and my c# program in linqpad looks like this:
var x = someTableName.Take(100);

**Comment by atifaziz** [comment]
I'm afraid not and I think it will mostly remain out of scope because the idea is not to support all of LINQPad's bells & whistles because you have [`lprun`](https://www.linqpad.net/lprun.aspx) for that.

**Comment by atifaziz** [comment]
Considering closing this is you're primary question has been answered.

**Comment by atifaziz** [comment]
Assuming question is answered.
